# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dmaSystem/dmaSystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem || ORIG_REF_NAME==dmaSystem} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_processing_system7_0_0/dmaSystem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_processing_system7_0_0 || ORIG_REF_NAME==dmaSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_ps7_0_axi_periph_0/dmaSystem_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==dmaSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_rst_ps7_0_50M_0/dmaSystem_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_rst_ps7_0_50M_0 || ORIG_REF_NAME==dmaSystem_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_axi_dma_0_1/dmaSystem_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_axi_dma_0_1 || ORIG_REF_NAME==dmaSystem_axi_dma_0_1} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_system_ila_0_0/dmaSystem_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_system_ila_0_0 || ORIG_REF_NAME==dmaSystem_system_ila_0_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_xbar_1/dmaSystem_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_xbar_1 || ORIG_REF_NAME==dmaSystem_xbar_1} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_axi_mem_intercon_1/dmaSystem_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_axi_mem_intercon_1 || ORIG_REF_NAME==dmaSystem_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_gamma_correction_0_0/dmaSystem_gamma_correction_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_gamma_correction_0_0 || ORIG_REF_NAME==dmaSystem_gamma_correction_0_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_auto_pc_0/dmaSystem_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_auto_pc_0 || ORIG_REF_NAME==dmaSystem_auto_pc_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_auto_us_0/dmaSystem_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_auto_us_0 || ORIG_REF_NAME==dmaSystem_auto_us_0} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_auto_us_1 || ORIG_REF_NAME==dmaSystem_auto_us_1} -quiet] -quiet

# IP: bd/dmaSystem/ip/dmaSystem_auto_pc_1/dmaSystem_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dmaSystem_auto_pc_1 || ORIG_REF_NAME==dmaSystem_auto_pc_1} -quiet] -quiet

# XDC: /home/a0504467/bits_pilani/sem_1/hscd_lab/vivado/dmaSystem/dmaSystem.gen/sources_1/bd/dmaSystem/dmaSystem_ooc.xdc
