# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/a0504467/bits_pilani/sem_1/hscd_lab/vivado/dmaSystem/dmaSystem.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_processing_system7_0_0/dmaSystem_processing_system7_0_0.xci
# IP: The module: 'dmaSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/a0504467/bits_pilani/sem_1/hscd_lab/vivado/dmaSystem/dmaSystem.gen/sources_1/bd/dmaSystem/ip/dmaSystem_processing_system7_0_0/dmaSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/a0504467/bits_pilani/sem_1/hscd_lab/vivado/dmaSystem/dmaSystem.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_processing_system7_0_0/dmaSystem_processing_system7_0_0.xci
# IP: The module: 'dmaSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/a0504467/bits_pilani/sem_1/hscd_lab/vivado/dmaSystem/dmaSystem.gen/sources_1/bd/dmaSystem/ip/dmaSystem_processing_system7_0_0/dmaSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
